#!/usr/bin/env python3
"""
Convert Markdown to a standalone, styled HTML page.

Uses Python's markdown library (already available) with extensions for
tables, fenced code blocks, code highlighting, and table of contents.

Usage:
  md_to_html.py --input paper.md --output paper.html
  md_to_html.py --input paper.md               # defaults to same base name
  cat paper.md | md_to_html.py -o paper.html   # read from stdin
"""
import argparse
import sys
from markdown import markdown
from markdown.extensions.codehilite import CodeHiliteExtension
from markdown.extensions.toc import TocExtension

CSS = """
:root {
  --bg: #fafafa;
  --text: #333;
  --heading: #1a1a1a;
  --link: #0366d6;
  --border: #e1e4e8;
  --code-bg: #f6f8fa;
  --table-stripe: #f6f8fa;
  --meta: #666;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #0d1117;
    --text: #c9d1d9;
    --heading: #f0f6fc;
    --link: #58a6ff;
    --border: #30363d;
    --code-bg: #161b22;
    --table-stripe: #161b22;
    --meta: #8b949e;
  }
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
  font-size: 16px; line-height: 1.7; color: var(--text);
  background: var(--bg); max-width: 860px; margin: 0 auto; padding: 2rem 1.5rem;
}
h1 { font-size: 2em; border-bottom: 1px solid var(--border); padding-bottom: .3em; margin: 1em 0 .5em; color: var(--heading); }
h2 { font-size: 1.5em; border-bottom: 1px solid var(--border); padding-bottom: .2em; margin: 1.2em 0 .4em; color: var(--heading); }
h3 { font-size: 1.25em; margin: 1em 0 .3em; color: var(--heading); }
h4 { font-size: 1.1em; margin: .8em 0 .2em; color: var(--heading); }
p { margin: .6em 0; }
a { color: var(--link); text-decoration: none; }
a:hover { text-decoration: underline; }
blockquote {
  border-left: 4px solid var(--link); padding: .5em 1em; margin: 1em 0;
  color: var(--meta); background: var(--code-bg); border-radius: 0 4px 4px 0;
}
code {
  background: var(--code-bg); padding: .15em .4em; border-radius: 3px;
  font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
  font-size: 85%;
}
pre {
  background: var(--code-bg); padding: 1em; border-radius: 6px;
  overflow-x: auto; margin: .8em 0; border: 1px solid var(--border);
}
pre code { background: none; padding: 0; }
table {
  border-collapse: collapse; width: 100%; margin: 1em 0;
  display: block; overflow-x: auto;
}
th, td {
  border: 1px solid var(--border); padding: .5em .8em; text-align: left;
}
th { background: var(--code-bg); font-weight: 600; }
tr:nth-child(even) td { background: var(--table-stripe); }
hr { border: none; border-top: 1px solid var(--border); margin: 2em 0; }
ul, ol { padding-left: 2em; margin: .5em 0; }
li { margin: .2em 0; }
img { max-width: 100%; }
.header-meta {
  color: var(--meta); font-size: .9em; margin-bottom: 1.5em;
  padding-bottom: 1em; border-bottom: 1px solid var(--border);
}
.header-meta strong { color: var(--text); }
.footer {
  margin-top: 3em; padding-top: 1em; border-top: 1px solid var(--border);
  color: var(--meta); font-size: .85em; text-align: center;
}
"""

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
{css}
</style>
</head>
<body>
{body}
<div class="footer">Generated by bio-paper-interpreter / Phase 3 Convert</div>
</body>
</html>"""


def main():
    parser = argparse.ArgumentParser(description='Convert Markdown to styled HTML')
    parser.add_argument('--input', '-i', help='Input Markdown file (reads stdin if omitted)')
    parser.add_argument('--output', '-o', help='Output HTML file (default: input base + .html)')
    args = parser.parse_args()

    # Read input
    if args.input:
        with open(args.input, 'r', encoding='utf-8') as f:
            md_text = f.read()
    else:
        md_text = sys.stdin.read()

    # Determine title from first h1
    title = 'Paper Interpretation'
    for line in md_text.splitlines():
        if line.startswith('# '):
            title = line[2:].strip()
            break

    # Convert
    extensions = [
        'markdown.extensions.tables',
        'markdown.extensions.fenced_code',
        CodeHiliteExtension(guess_lang=True, css_class='highlight'),
        TocExtension(permalink=True),
        'markdown.extensions.smarty',
    ]
    html_body = markdown(md_text, extensions=extensions)

    html = HTML_TEMPLATE.format(title=title, body=html_body, css=CSS)

    # Write output
    if args.output:
        out_path = args.output
    elif args.input:
        out_path = args.input.rsplit('.', 1)[0] + '.html'
    else:
        print("Error: --output required when reading from stdin", file=sys.stderr)
        return 1

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(html)

    print(f"HTML saved: {out_path}", file=sys.stderr)


if __name__ == '__main__':
    main()